language: java
jdk:
- oraclejdk8
install: mvn --version
before_script: "./.travis.version_if_tag.sh"
after_success: "./.travis.deploy_if_tag.sh"
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: z8WUgXfQXitqhGGit+/o/LoznTCGb6ggfzvxdmnhymq524ty+QNPyYRWLSSrauFqsWwM08WR8/GT6W5qohVMXIKhZSwnFubBD3c0YuQ9gucDJXkFe6Ej2ev0E4Nvnhrj2VQ0MVf0GribICOFn/kdGzghRJlqgRQ3PDHP3aO8pU2s9yNhcVkQsRHbEQll5AlQaDJLP24/szCfaGa87lb2ePxpOobGpjK9v/M9eZSTzESig/dp/M+nN8ZGKk81ER/NaF1IoK1nooNCKXeurIfc11Xs0gyESv9Lccc9cCXmkltQe8YRrliy9poGTHAZ38mYVynGH28p4E5pWn8zZguBiliMZ4HMtNNPTGLNlAR4bq3QkO+qMA+fZp+a/jvYnZ+EUnovXY9sWVU3oQdQtDQz95abBg1qeVFmA+V2P3tFA5o5JNk8aikh19mew9gY4ZAZ5ch9Xs/hRqIhgiAqTTD3m3E9F/AGHntdtu1Mj2bRaQLatVNRjLFP22OeOoB/vIP4NypBP34lofhrZpG6WFza1ZXjgCDronUvJRhSJgomnETYWvdpdm14G5k7Mh4eSuv39y4S/SQ4GToynSWv5gj9bjweJ66cw+UsHfPzMogY0i3XzzyGEd8ucvvt14GBXTIO1l32IDQ2wYzS8m5Fx1xJAEbwQ7xhYuKacuPpyhnixvs=
  file: nomer.jar
  skip_cleanup: true
  on:
    repo: globalbioticinteractions/nomer
    tags: true
env:
  global:
  - secure: T5HVkJXAweUZZipfKe2K569aXR6/txLD+R0Jf6Lizt78SIP6vfgrxa2JflDq4Wze/8aSsBmp3l7z3ECY0trH+wQuzFyNG5V6Oh5z2tU4NQJgO3upPnDgBBhVD/Gpfki3fmX5eLiHCAPvcpV09Q06C22cheLRyyLND0gbK1dvv0pQBICsebNdqzKPHNYA+M6eZFg74XmE9GBwojMsOKL2g9cGs9NCjqJCjRDXZjsryRl/JvK8CBQ0ksgvuh7zBcqfCjArfvFhgkMVfewLcutEDnny1zvnV4qt8rcofhgWXTc5igRf2pHnKov3JCn+R4ij6kpRR7rKsx3vZ2GK4lYCGBRUue+XtQGxM1AgzMxSUfni5mQtdiqr4zj1oYXwzDk03rEDckbH6p/kGoJhJ/K/Wi4DDyHDmCQ4J9fdrf/R3MnKw4e1BsF3W5WbYLQK4vR4WWWXPpXdqpATfZQuyef/pyvptKvJv6VAr9wyI9XbfH334ImgwzY5TQCL9Os+fQcxw2+mzpH6ocT732DOjsQFbKHUmpTyMoxpoVR7t86aLvhOOINWvCXxJXJwJ9QaQOVJMVVPlr6//iSiM/SWkEr87/etu/YZ+RSSigYY/VHRAfnPc9Y05eGCu10EUBq0l/USZO3ye3I36xZ/pbPF/xItG7inFAtiEnXGToIFkoV1tqc=
  - secure: G4biPzl5ttdQSg34/00JY58aF3gsq/UnHduvcJbtRNbh6oUCx08BZ+5y1gmrbQm8fl1qrtBfw9eI+s6ai59pdXiZnUF66FoDPHVbNziV8frwoE00oQzbstxfrjfwH9xtY0sra17FhYf+IwCfhiRfu0FAqDso/yqnQprWv0ImfGP/sYyvbRmqzOYveCrI+XlR6CMGAyy0ugkJanXCVWaSh3cK8DVREdwV4/Z+FflGWV4guq00tfwQ/4g/vxW5JqKheD6NvTcD6B+J+5Vmp1Rstq7BlxjHRVZi6L+sL3KfcqQL0/ejslFd71j0rBYGItbdrhTDs1FXzARBrSborJJ8rD9x/X9sCeRI+AGfVrkSVR2U+Nq/oLmIywdmivGswmJXSzlonID3vUq5Cs3Rfgfjn+emDHimEc4o7eJ5tVess/qQy4XQkoicQiZiz5IZj6pUo9Le5tlXrAA3jhrkMj610umZ35zMH2eiYbQ8ZACsJkAQvTy2T/l4nQVGkS4/G+Hwaxu4wHnZ+HTmupsdG8r53OiiUN7fODkkGVeE8asV9Cw7IsULnCPRYRiZ3OxB9Q5dfxG2m79JSkBeud3JTzmV+EOsXjsBPMigdtsB8GHytmNnxlSmevLr2TE9GRrwV8eDG6szKPqGDThXabRx/X+C2TXTPBDJoEVjWQ5MvrVqcys=
